name: fomo
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.13
  - pip=22.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
    - timm==0.9.10
    - scipy==1.9.1
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.3.0
    - einops==0.3.0
    - transformers==4.19.2
    - webdataset==0.2.5
    - kornia==0.6
    - datasets==2.18.0
    - open_clip_torch==2.16.0
    - torchmetrics==0.6.0
    - pandas==1.5.0
    - pycocotools==2.0.7
    - matplotlib
    - gdown
    - patool
    - h5py==3.9.0
    - onedrivedownloader==1.1.3
    - hydra-core==1.3.2
    - termcolor==2.3.0
    - medmnist==2.2.1
    - wandb==0.13.4
    - sqlalchemy==1.3.24
    - Flask-SQLAlchemy>=2.4.3
    - SQLAlchemy-Utils>=0.36.6
    - boto3>=1.13.24
    - botocore>=1.16.24
    - galore-torch
    - pytorch-metric-learning>=2.4.1
    - -e git+https://github.com/modestyachts/ImageNetV2_pytorch#egg=imagenetv2_pytorch
    - -e git+https://github.com/openai/CLIP.git#egg=clip
    - -e .
